apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: acme-app-cluster-1
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-large
      storageClass: k8s-storage-policy
    workers:
      count: 3
      class: best-effort-large
      storageClass: k8s-storage-policy
  distribution:
    version: v1.20
