#cloud-config
users:
  - default
  - name: vmware
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    # Password set to Admin!23
    passwd: '$1$salt$RUXm1Lco5jcJ7OBw.hRQi1'
    shell: /bin/bash
ssh_pwauth: true

write_files:
  - content: |
      version: '3'
      services:
        mongo:
          image: mongo
          restart: always
          ports:
          - "27017:27017"
          environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: password
          volumes:
            - mongo-data:/data/db
        mongo-express:
          image: mongo-express
          restart: always
          ports:
          - "8081:8081"
          environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
      volumes:
        mongo-data:
    path: /home/vmware/docker-compose.yaml

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_update: true

packages:
  - docker-ce
  - docker-ce-cli
  - docker-compose

runcmd:
  - sudo docker run --name nginx -p 80:80 -d harbor.tanzuworld.com/openso/nginx
  - docker-compose -f /home/vmware/docker-compose.yaml up -d

